name: Release

on:
  release:
    types:
      - published

env:
  DEFAULT_PYTHON: "3.11"

permissions:
  contents: read

jobs:
  release-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v4.1.0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          check-latest: true

      - name: Create Python virtual environment
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install requirements
        run: poetry install --no-interaction --no-root

      - name: Build distributions
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --build
